"""add event_logs table

Revision ID: 8c4631237d96
Revises: 924dd05fbfe9
Create Date: 2025-10-18 18:22:58.713957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4631237d96'
down_revision: Union[str, Sequence[str], None] = '924dd05fbfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_source_url', sa.String(length=2048), nullable=True),
    sa.Column('user_ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('fbp', sa.String(length=100), nullable=True),
    sa.Column('fbc', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_event_id'), 'event_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_logs_event_name'), 'event_logs', ['event_name'], unique=False)
    op.create_index(op.f('ix_event_logs_id'), 'event_logs', ['id'], unique=False)
    op.create_index(op.f('ix_event_logs_received_at'), 'event_logs', ['received_at'], unique=False)
    op.create_index(op.f('ix_event_logs_website_id'), 'event_logs', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_website_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_received_at'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_name'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_id'), table_name='event_logs')
    op.drop_table('event_logs')
    # ### end Alembic commands ###
